#!/usr/bin/env bash

set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=./functions.sh
source "$DIR/functions.sh"

# Generates ~/.config/task/sync.rc, the TaskChampion sync credentials that
# ~/.taskrc `include`s. Mirrors gitconfig.sh: the generated file lives outside
# this repo so it can never be committed, and self-heals on a fresh machine by
# re-running install.
#
# The encryption secret must never leave this Mac (the picklelab sync server is
# zero-knowledge), so real creds are only written on macOS. The creds live in
# the personal `picklehome` 1Password vault.

target="$HOME/.config/task/sync.rc"
mkdir -p "$HOME/.config/task"

# Always ensure the include target exists. ~/.taskrc is shared across every
# machine (work Mac, Linux devcontainers) and taskwarrior warns on every
# command if an `include`d file is missing. A placeholder keeps output clean
# where we don't populate real creds.
if [ ! -f "$target" ]; then
  umask 077
  cat > "$target" << 'EOF'
# Placeholder. Real TaskChampion sync creds are written here by
# dotfiles/taskrc.sh from op://picklehome/TaskChampion Sync on macOS.
# No sync configured on this machine yet.
EOF
  chmod 600 "$target"
fi

if ! running_macos; then
  echo "📋 taskrc: not macOS, leaving ~/.config/task/sync.rc as placeholder"
  exit 0
fi

if ! command_available op; then
  echo "📋 taskrc: 1Password CLI not available, leaving sync.rc as placeholder"
  exit 0
fi

echo "📋 generating ~/.config/task/sync.rc (TaskChampion sync creds)"

op_ensure_signed_in

item="op://picklehome/TaskChampion Sync"
# Tolerate a missing item/field: a broken sync config shouldn't fail the whole
# dotfiles install. set -e would otherwise abort on op read's non-zero exit.
host="$(op read "$item/host" 2> /dev/null || true)"
client_id="$(op read "$item/client_id" 2> /dev/null || true)"
encryption_secret="$(op read "$item/encryption_secret" 2> /dev/null || true)"

if [[ -z "$host" || -z "$client_id" || -z "$encryption_secret" ]]; then
  echo "  ⚠️  missing host/client_id/encryption_secret in '$item', leaving placeholder" >&2
  exit 0
fi

# The 1Password `host` field is a bare hostname; taskwarrior wants a full URL.
case "$host" in
  http://* | https://*) url="$host" ;;
  *) url="https://$host" ;;
esac

# umask before the write so the secret is never world/group-readable, even for
# the brief window between creating the file and chmod.
umask 077
cat > "$target" << EOF
# Generated by dotfiles/taskrc.sh from op://picklehome/TaskChampion Sync.
# DO NOT edit or commit. Regenerate with ./taskrc.sh.
# Included by ~/.taskrc. The encryption secret stays on this Mac.
sync.server.url=$url
sync.server.client_id=$client_id
sync.encryption_secret=$encryption_secret
EOF
chmod 600 "$target"

echo "  → wrote $target (0600)"
echo "  → run 'task sync' to push local task history to the server"
