#!/usr/bin/env bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

for linkable in $(find home -type f -maxdepth 1); do
  target="$HOME/$(basename $linkable)"

  if [ ! -L $target ]; then
    echo "🔗 Linking $target → $linkable."
    ln -Ff -s $DIR/$linkable $target
  fi
done
